baseurl = "http://www.itakoh.co.jp"
languageCode = "ja-jp"
title = "株式会社ITAKO"

[Params]
  email = "contact@itakoh.co.jp"
  facebook = "ITAKO"
  description = "娯楽を作って生きていく"
  logo = "/images/icon.png"
